"""empty message

Revision ID: 476d3a46a324
Revises: 
Create Date: 2024-01-09 18:06:02.847968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '476d3a46a324'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_taken', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userfeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('ratings', sa.Integer(), nullable=False),
    sa.Column('user_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userfeedback')
    op.drop_table('conversation')
    op.drop_table('chat')
    op.drop_table('admin')
    # ### end Alembic commands ###
